import { NextPage } from "next";
import Head from "next/head";
import { useCookies } from "react-cookie";
import VerifyPhoneForm from "../../../app/forms/auth/verifyPhoneForm";

const login: NextPage = () => {
  const [cookies, setCookie] = useCookies(["shopy-token"]);

  return (
    <>
      <Head>
        <title>sign in form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-r from-[#acb2c2] to-[#c0c5cf] w-full h-screen pt-[5rem] font-[sans-serif]">
        <div className="bg-white rounded-2xl grid max-w-[30rem] p-4 mx-auto ">
          <div className="right-side pl-10 pt-10 pr-4">
            <h3 className="text-[2.5rem] font-semibold ">verify phone</h3>
            <p className="my-3 text-slate-400">please enter your code </p>
            <VerifyPhoneForm setCookies={setCookie} />
          </div>
        </div>
      </main>
    </>
  );
};

export default login;
