import { NextPage } from "next";
import Head from "next/head";
import { useCookies } from "react-cookie";
import LoginForm from "../../app/forms/auth/loginForm";

const login: NextPage = () => {

  const [cookies , setCookie] = useCookies(['shopy-token'])

  return (
    <>
      <Head>
        <title>sign in form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-r from-[#acb2c2] to-[#c0c5cf] w-full h-screen pt-[5rem] font-[sans-serif]">
        <div className="bg-white rounded-2xl grid max-w-[30rem] p-4 mx-auto ">
          <div className="right-side pl-10 pt-10 pr-4">
            <h3 className="text-[2.5rem] font-semibold ">Log in</h3>
            <p className="mt-2 text-slate-400 mb-1">Create your account now</p>
            <LoginForm setCookies={setCookie}/>
          </div>
        </div>
      </main>
    </>
  );
};

export default login;
